application: polymertest
module: default
version: 1
runtime: go
api_version: go1

handlers:
- url: /(index\.html)?
  static_files: static/index.html
  upload: static/index.html


- url: /bower_components/(.*)
  static_files: bower_components/\1
  upload: /bower_components


- url: /static/(.*)
  static_files: static/\1
  upload: /static


# - url: /.*
#   script: _go_app

- url: /admin/.*
  script: _go_app
  login: admin
